ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.operator_status_drift]
path = "out/OperatorStatusDriftTrap.sol/OperatorStatusDriftTrap.json"
response_contract = "0x6d4e90d6c362cc01b4bf529f7b2cee84fa5a2419"
response_function = "respondWithOperatorAlert(address,uint8,uint8,bytes32)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xcfE6dA9D82BE3bD159e2C1386302FbA0740022E2"]
address = "0xB7a726806A6524e1a3b06Ee9b5160572aC2CAbB8"
